@ECHO OFF
COLOR 0a
SETLOCAL ENABLEDELAYEDEXPANSION
SET COUNT=1
:BEGIN
  CLS
  IF !COUNT! EQU 1 ECHO "\" 
  IF !COUNT! EQU 2 ECHO "|" 
  IF !COUNT! EQU 3 ECHO "/" 
  IF !COUNT! EQU 4 ECHO "-" 
  IF !COUNT! EQU 4 (
    SET COUNT=1
  ) ELSE (
    SET /A COUNT+=1
  )
  PSLIST CALC >nul 2>&1
  IF %ERRORLEVEL% EQU 1 GOTO END
GOTO BEGIN

:END